version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: nur02
          tag: "${CIRCLE_SHA1}"
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
#           registry-id: 294140702112
