version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: nur02
          tag: "${CIRCLE_SHA1}"
          region: us-east-1
          account-url: 294140702112.dkr.ecr.us-east-1.amazonaws.com
#           registry-id: 294140702112
